name: Build PretextView

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: |
        choco install ninja
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install mingw
        RefreshEnv

    - name: Set up MinGW
      shell: bash
      run: |
        echo "Setting up MinGW environment"
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        pacman -Syu --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-pkg-config

    - name: Configure Meson Build
      shell: bash
      run: |
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        meson setup --buildtype=release --prefix=$(pwd)/PretextView_build builddir

    - name: Compile with Ninja
      shell: bash
      run: |
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        ninja -C builddir

    - name: Run Meson Tests
      shell: bash
      run: |
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        ninja -C builddir test

    - name: Install Executable
      shell: bash
      run: |
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        ninja -C builddir install

    - name: Package Executable
      run: |
        cd PretextView_build
        tar -czf PretextView_windows.tar.gz *
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PretextView_windows
        path: PretextView_build/PretextView_windows.tar.gz
