name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Miniconda
      run: |
        $conda_url = 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe'
        Invoke-WebRequest $conda_url -OutFile miniconda.exe
        Start-Process miniconda.exe -ArgumentList '/InstallationType=JustMe', '/AddToPath=0', '/RegisterPython=0', '/S', '/D=%USERPROFILE%\miniconda' -NoNewWindow -Wait
        echo "Adding Miniconda to the PATH"
        $env:Path += ";$env:USERPROFILE\miniconda;$env:USERPROFILE\miniconda\Scripts;$env:USERPROFILE\miniconda\condabin"
        conda init powershell
        powershell -ExecutionPolicy ByPass -File $PROFILE

    - name: Setup build environment
      shell: bash
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        mamba create -q -n test-environment -c conda-forge -c bioconda meson mingw-w64 samtools
        conda activate test-environment
        set CC=x86_64-w64-mingw32-gcc
        set CXX=x86_64-w64-mingw32-g++
        set WINDRES=x86_64-w64-mingw32-windres
        meson setup --buildtype=release --prefix=%cd%\app --bindir=. --unity on builddir

    - name: Meson Compile
      shell: bash
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate test-environment
        meson compile -C builddir

    - name: Meson Test
      shell: bash
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate test-environment
        meson test -C builddir

    - name: Meson Install
      shell: bash
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh
        conda activate test-environment
        meson install -C builddir

    - name: Create executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: PretextView
        path: app/*
