name: Build PretextView

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: |
        choco install ninja
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install mingw
        python -m pip install meson  # Install meson via pip

    - name: Set up MinGW and Python Path
      run: |
        $env:PATH += ";C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        $env:PATH += ";C:\hostedtoolcache\windows\Python\3.x.x\x64\Scripts"
        Write-Host "Updated PATH: $env:PATH"

    - name: Configure Meson Build
      shell: bash
      run: |
        export PATH=/C/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH
        meson setup --buildtype=release --prefix=$(pwd)/PretextView_build builddir

    - name: Compile with Ninja
      shell: bash
      run: |
        export PATH=/C/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH
        ninja -C builddir

    - name: Run Meson Tests
      shell: bash
      run: |
        export PATH=/C/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH
        ninja -C builddir test

    - name: Install Executable
      shell: bash
      run: |
        export PATH=/C/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH
        ninja -C builddir install

    - name: Package Executable
      run: |
        cd PretextView_build
        tar -czf PretextView_windows.tar.gz *
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PretextView_windows
        path: PretextView_build/PretextView_windows.tar.gz
