name: testmacos14

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: setup_conda
      run: |
        export conda_url=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        
        wget $conda_url -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        conda install -c conda-forge mamba
        
        export toolchain=clangxx_osx-64
        
        mamba create -q -n test-environment -c conda-forge -c bioconda -y meson clang $toolchain samtools

    - name: setup_environment
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda activate test-environment
        
        export PATH="/opt/homebrew/bin:$PATH"
        
        [ -d "app" ] && rm -rf "app"
        [ -d "builddir" ] && rm -rf "builddir"
        mkdir -p app
        mkdir -p builddir
        cat > "app/.gitignore" <<END
        *
        Build type: debug
        cmake --version
        Host_machine_name: $(uname) 
        END

    - name: meson_setup
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda activate test-environment

        if [ `uname` == Darwin ]; then
          [ -d app/PretextView.app ] && rm -rf app/PretextView.app
          env CC=clang CXX=clang MACOSX_DEPLOYMENT_TARGET=14.3 meson setup --buildtype=debug --prefix=$(pwd)/app/PretextView.app --bindir=Contents/MacOS --unity on builddir
        else
          env CC=clang CXX=clang meson setup --buildtype=debug --prefix=$(pwd)/app --bindir=./ --unity on builddir
        fi

    - name: meson_compile
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda activate test-environment
        meson compile -C builddir
    
    - name: meson_install
      run: |
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda activate test-environment
        meson install -C builddir

    - name: create_artifact
      uses: actions/upload-artifact@v4
      with:
        name: PretextView.zip
        path: app/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
