name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Conda
      run: |
        # Download Miniconda installer
        $conda_url = "https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"
        Invoke-WebRequest -Uri $conda_url -OutFile miniconda.exe

        # Install Miniconda silently
        Start-Process -Wait -FilePath .\miniconda.exe -ArgumentList "/InstallationType=JustForMe", "/AddToPath=1", "/S", "/D=$env:USERPROFILE\miniconda"

        # Activate Conda
        & "$env:USERPROFILE\miniconda\Scripts\activate.bat"

        # Configure Conda environment
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a

        # Install required tools via mamba
        conda install -c conda-forge mamba
        mamba create -q -n test-environment -c conda-forge -c bioconda -y meson clangxx_win-64 samtools

    - name: Setup Meson
      run: |
        # Activate the test environment
        & "$env:USERPROFILE\miniconda\Scripts\activate.bat" test-environment
        
        # Set the necessary environment variables for Meson build
        $env:CC = "clang"
        $env:CXX = "clang"
        $env:MACOSX_DEPLOYMENT_TARGET = "10.10"  # Although this is for macOS, leaving it here for completeness
        meson setup --buildtype=release --prefix=%cd%\build\PretextView --bindir=bin --unity on builddir

    - name: Meson Compile
      run: |
        & "$env:USERPROFILE\miniconda\Scripts\activate.bat" test-environment
        cd builddir
        meson compile

    - name: Meson Test
      run: |
        & "$env:USERPROFILE\miniconda\Scripts\activate.bat" test-environment
        cd builddir
        meson test

    - name: Meson Install
      run: |
        & "$env:USERPROFILE\miniconda\Scripts\activate.bat" test-environment
        cd builddir
        meson install

    - name: Make Executable
      run: |
        # Ensure the executable is built and ready to go (on Windows, executables are inherently runnable)
        echo "Ensuring executable is built"

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PretextView
        path: build\bin\PretextView.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
