name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.10
        activate-environment: test-environment
        environment-file: false

    - name: Install Build Dependencies
      shell: powershell
      run: |
        conda install -c conda-forge -y meson ninja clangxx cmake pkg-config
        conda list
    
    - name: Verify Meson Installation
      shell: powershell
      run: |
        conda run -n test-environment meson --version
        conda run -n test-environment which meson
    
    - name: Configure Build
      shell: powershell
      run: |
        $env:CC = "clang"
        $env:CXX = "clang++"
        conda run -n test-environment meson setup `
          --buildtype=release `
          --prefix="${{ github.workspace }}\build\PretextView" `
          --bindir=bin `
          --unity on `
          builddir
    
    - name: Compile Project
      shell: powershell
      run: |
        conda run -n test-environment meson compile -C builddir
    
    - name: Run Tests
      shell: powershell
      run: |
        conda run -n test-environment meson test -C builddir
    
    - name: Install Project
      shell: powershell
      run: |
        conda run -n test-environment meson install -C builddir
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PretextView
        path: builddir\bin\PretextView.exe
